# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hoopla-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_fafb7a50a2294bef91d8bac65966df3c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a31ad39f0a0145e39aa9fe6b06891638 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_fafb7a50a2294bef91d8bac65966df3c }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hoopla-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9fd252830fd42428b09f62290299239 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_fafb7a50a2294bef91d8bac65966df3c }}/appsvc/staticsite:${{ github.sha }}'